---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 11:09
---

local DialogView = {}
DialogView.callBack = nil
CptCenter.dialog_btn_confirm.onClick:AddListener(function()
    DialogController.onConfirmClick(DialogView.callBack)
end)

CptCenter.dialog_btn_cancel.onClick:AddListener(function()
    DialogController.onCancelClick()
end)

function DialogView.setTipText(str)
    CptCenter.dialog_txt_tip.text = str
end

function DialogView.showDialog(str, callBack, hideCancelButton)
    DialogView.callBack = callBack
    DialogView.setTipText(str)
    if hideCancelButton then
        CptCenter.dialog_btn_cancel.gameObject:SetActive(false)
    end
    CptCenter.dialog_panel:SetActive(true)
end

function DialogView.close()
    CptCenter.dialog_panel:SetActive(false)
    DialogView.callBack = nil
    DialogView.setTipText("NormalTip")
    CptCenter.dialog_btn_cancel.gameObject:SetActive(true)
end

return DialogView