---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 12:10
---

local LoginView = {}

CptCenter.login_btn_login.onClick:AddListener(function()
    LoginController.loginClick(CptCenter.login_username.text,CptCenter.login_password.text)
end)

CptCenter.login_btn_signup.onClick:AddListener(function()
    LoginController.signupClick()
end)

function LoginView.hide()
    CptCenter.login_panel:SetActive(false)
    CptCenter.login_username.text = ""
    CptCenter.login_password.text = ""
end

function LoginView.show()
    CptCenter.login_panel:SetActive(true)
end

function LoginView.onSuccess()
    LoginView.hide()
    CptCenter.loginSuccess:SetActive(true)
end

return LoginView