---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 15:17
---
local NormalTipView = {}

print("NormalTip")
local cs_coroutine = require 'cs_coroutine'
local isShowing = false
local tip = CptCenter.tipBar
local tipText = CptCenter.tipText
local coroutine = function()
    isShowing = true
    tip:SetActive(true)
    coroutine.yield(CS.UnityEngine.WaitForSeconds(2))
    tip:SetActive(false)
    isShowing = false
end

function NormalTipView.showTip(message)
    if not isShowing then
        print('showTip:' .. message)
        tipText.text = message
        cs_coroutine.start(coroutine)
    else
        print("isHaveOtherShowing")
    end
end

return NormalTipView
