---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 14:11
---

local SuccessView = {}

CptCenter.btn_quit.onClick:AddListener(function()
    SuccessController.onQuitClick()
end)

function SuccessView.show()
    CptCenter.success_panel:SetActive(true)
end

function SuccessView.hide()
    CptCenter.success_panel:SetActive(false)
end

return SuccessView