---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 17:18
---

local ThemeView = {}

CptCenter.theme_btn_open.onClick:AddListener(function()
    ThemeController.onOpenClick()
end)

CptCenter.theme_btn_close.onClick:AddListener(function()
    ThemeController.onCloseClick()
end)

CptCenter.theme_btn_bg01.onClick:AddListener(function()
    ThemeController.selectTheme('01')
end)

CptCenter.theme_btn_bg02.onClick:AddListener(function()
    ThemeController.selectTheme('02')
end)

CptCenter.theme_btn_bg03.onClick:AddListener(function()
    ThemeController.selectTheme('03')
end)

CptCenter.theme_btn_bg04.onClick:AddListener(function()
    ThemeController.selectTheme('04')
end)

CptCenter.theme_btn_bg05.onClick:AddListener(function()
    ThemeController.selectTheme('05')
end)

CptCenter.theme_btn_bg06.onClick:AddListener(function()
    ThemeController.selectTheme('06')
end)

function ThemeView.setTheme(id)
    local curID = ThemeController.getCurThemeID()
    CptCenter['theme_mask_' .. curID]:SetActive(false)

    CptCenter.theme_bg_img.sprite = CptCenter['theme_img_' .. id].sprite
    CptCenter['theme_mask_' .. id]:SetActive(true)
end

function ThemeView.showPanel()
    CptCenter.theme_btn_close.gameObject:SetActive(true)
    CptCenter.theme_panel.transform:DOMoveX(0, 0.3)
end

function ThemeView.hidePanel()
    CptCenter.theme_btn_close.gameObject:SetActive(false)
    CptCenter.theme_panel.transform:DOMoveX(-550, 0.3)
end

function ThemeView.setDefaultTheme()
    ThemeController.setDefaultTheme()
end

return ThemeView