---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 11:30
---

local DialogController = {}

function DialogController.showDialog(str,callBack,hideCancelButton)
    DialogView.showDialog(str,callBack,hideCancelButton)
end 

function DialogController.onConfirmClick(callBack)
    callBack()
    DialogController.onCancelClick()
end 

function DialogController.onCancelClick()
    DialogView.close()
end

return DialogController