---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 11:07
---


local NormalTipController = {}

function NormalTipController.showTip(str)
    NormalTipView.showTip(str)
end 

return NormalTipController

