---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 17:03
---

local ThemeController = {}

function ThemeController.selectTheme(id)
    local themeId = ThemeModel.checkThemeID(id)
    if themeId then
        ThemeController.setTheme(id)
    end
end 

function ThemeController.getCurThemeID()
    return ThemeModel.getCurThemeID()
end

function ThemeController.setTheme(themeId)
    ThemeView.setTheme(themeId)
    ThemeModel.setCurTheme(themeId)
end 

function ThemeController.onOpenClick()
    ThemeView.showPanel()
end 

function ThemeController.onCloseClick()
    ThemeView.hidePanel()
end 

function ThemeController.setDefaultTheme()
    local id = ThemeModel.getDefaultThemeID()
    ThemeController.setTheme(id)
end

function ThemeController.init()
    ThemeController.setDefaultTheme()
end

return ThemeController