---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/22 19:47
---

CptCenter = {}
function CptCenter.init(table)
    CptCenter = table
end 

return CptCenter