---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/23 16:57
---

local ThemeModel = {}
ThemeModel.themeIDList = { '01', '02', '03', '04', '05', '06' }
ThemeModel.defaultThemeID = "06"
ThemeModel.curThemeID = nil

function ThemeModel.setCurTheme(id)
    ThemeModel.curThemeID = id
end

function ThemeModel.getCurThemeID()
    if ThemeModel.curThemeID and ThemeModel.checkThemeID(ThemeModel.curThemeID) then
        return ThemeModel.curThemeID
    else
        return  ThemeModel.defaultThemeID
    end
end

function ThemeModel.getDefaultThemeID()
    return ThemeModel.defaultThemeID
end

function ThemeModel.checkThemeID(id)
    for k, v in pairs(ThemeModel.themeIDList) do
        if v == id then
            return true
        end
    end
    
    return false
end

return ThemeModel